#define IDENT                            1
#define ASSN                             2
#define BANG                             3
#define SUMOVER                          4
#define DRAW                             5
#define ADD                              6
#define SUB                              7
#define MULT                             8
#define DIV                              9
#define EQ                              10
#define LT                              11
#define GT                              12
#define LTEQ                            13
#define GTEQ                            14
#define NL                              15
#define EXIT                            16
#define LBRACE                          17
#define RBRACE                          18
#define NUMBER                          19
#define FLOAT                           20
#define LPARENS                         21
#define RPARENS                         22
